server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          default-label: feature/F0001_add_config_server
          uri: https://github.com/alexandresoliveiragft/rabobank-test
          search-paths: '{application}/{profile}'
  security:
    user:
      name: dev
      password: dev