server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          default-label: develop
          uri: https://github.com/alexandresoliveiragft/rabobank-test/rabobank-travels-config-app-files
          search-paths: '{application}/{profile}/{label}'
  security:
    user:
      name: dev
      password: dev