server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alexandresoliveiragft/rabobank-test/rabobank-travels-config-app-files
          search-paths: '{label}/{application}/{profile}'
  security:
    user:
      name: dev
      password: dev