server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: classpath:/configurations
          search-paths: '{application}/{profile}'
  security:
    user:
      name: dev
      password: dev