spring:
  application:
    name: rabobank-travels-hotels-app
  profiles:
    active: dev
  config:
    import: 'optional:configserver:http://dev:dev@localhost:8080'
  cloud:
    config:
      label: develop